# Fonts

font_smooth true
font_family Hack Nerd Font
font_size 11

cursor_shape beam
cursor_beam_thickness 1.0
cursor #c0caf5
cursor_text_color #1a1b26

background_opacity 0.5
 background_blur 1
dynamic_background_opacity yes


 # -- window --
window_margin_width 10 15
window_resize_step_cells 5
window_resize_step_lines 2
confirm_os_window_close 0

# -- misc settings --
# enable_audio_bell no

# colors

background #606060
foreground #d8dee9

color0 #504945
color2 #a3be8c
color1 #bf616a
color3 #ebcb8b
color4 #5e81ac
color5 #b48ead
color6 #88c0d0
color7 #eceff4

color8 #665c54
color9 #bf616a
color10 #a3be8c
color11 #ebcb8b
color12 #5e81ac
color13 #b48ead
color14 #88c0d0
color15 #eceff4
