[main]
include=~/.cache/wal/colors-foot.ini

#font=FiraCode Nerd Font :size=11:weight=bold
font=Hack Nerd Font:size=11:weight=bold
line-height = 13.1
letter-spacing=0
box-drawings-uses-font-glyphs = no
font-size-adjustment = 0.5

bold-text-in-bright=no

shell=fish

pad=5x5

resize-by-cells = no

#[colors]
#background=1e2030
#alpha=0.9
