[main]
include=~/.cache/wal/colors-foot.ini

font=firacode nerd font:size=11:weight=bold
#font=Hack Nerd Font:size=11:weight=bold
#font=UbuntuMono Nerd Font:size=13:weight=bold
line-height = 13
letter-spacing=0
box-drawings-uses-font-glyphs = no
font-size-adjustment = 0.5

bold-text-in-bright=no

shell=fish

pad=15x15

resize-by-cells = no

title=Terminal
locked-title=yes

gamma-correct-blending=no

[colors]
#background=1e2030
alpha=0.8

[cursor]
style=beam
blink=yes
