[main]
include=~/.cache/wal/colors-foot.ini

font=FiraCode Nerd Font :size=11
line-height = 13
letter-spacing=0
box-drawings-uses-font-glyphs = no
font-size-adjustment = 0.5

bold-text-in-bright=no

shell=fish

pad=15x15

[colors]
#background=1e2030
alpha=0.7
