source = /home/islam/.cache/wal/colors-hyprland.conf
source = /home/islam/.config/hypr/hyprland/settings.conf
source = /home/islam/.config/hypr/hyprland/keybinds.conf
source = /home/islam/.config/hypr/hyprland/windowrules.conf
source = /home/islam/.config/hypr/hyprland/style.conf
source = /home/islam/.config/hypr/hyprland/startup.conf
