exec-once=waybar &
exec-once=swaync &
exec-once=hypridle &
exec-once=swww-daemon --format xrgb

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
