exec-once=~/.config/eww/scripts/start.sh
exec-once=hypridle &
exec-once=swww-daemon --format xrgb

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = sleep 2 && hyprpm reload
