layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = blurpopups, waybar
layerrule = ignorealpha 0.5, waybar

layerrule = blur, rofi
layerrule = ignorezero, rofi
layerrule = blurpopups, rofi
layerrule = ignorealpha 0.8, rofi

layerrule = noanim, swww-daemon
layerrule = noanim,hyprpicker

layerrule = noanim,selection

windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,class:^(nemo)$
windowrulev2 = float,class:^(nwg-look)$
windowrulev2 = float,title:^(Volume Control)$
windowrulev2 = float,title:^(Calendar)$

windowrulev2 = noblur ,class:^(.*)
windowrulev2 = noblur 0, class:^(foot)
windowrulev2 = noblur 0, class:^(nemo)
windowrulev2 = noblur 0, class:^(Calendar)
windowrulev2 = noblur 0, class:^(volume control)
windowrulev2 = noblur 0, class:^(resources)

windowrulev2 = opacity 1 1,class:^(firefox)$
windowrulev2 = opacity 0.80 0.80,class:^(nemo)$
windowrulev2 = opacity 0.80 0.80,class:^(nwg-look)$
windowrulev2 = opacity 0.80 0.80,title:^(Resources)$
windowrulev2 = opacity 0.80 0.80,title:^(Volume Control)$
windowrulev2 = opacity 0.80 0.80, title: ^(Calendar)$
