[[language]]
name = "c"
auto-format = true
language-servers = [ "clangd" ]

[[language]]
name = "bash"
auto-format = true
language-servers = [ "bash-language-server" ]


[[language]]
name = "nu"
language-servers = [ "nu"]
